DROP INDEX IF EXISTS idx_platform_treasury_withdrawals_platform_timestamp;
DROP INDEX IF EXISTS idx_platform_treasury_withdrawals_executed_by;
DROP INDEX IF EXISTS idx_platform_treasury_withdrawals_timestamp;
DROP INDEX IF EXISTS idx_platform_treasury_withdrawals_recipient;
DROP INDEX IF EXISTS idx_platform_treasury_withdrawals_platform_id;

DROP TABLE IF EXISTS platform_treasury_withdrawals;
