// Copyright (c) Mysten Labs, Inc.
// Copyright (c) The Social Proof Foundation, LLC.
// SPDX-License-Identifier: Apache-2.0

/// A JSONRPC module implementation coupled with a description of its schema.
pub trait RpcModule: Sized {
    /// Docs to add to the schema usually generated by the `open_rpc` macro.
    fn schema(&self) -> myso_open_rpc::Module;

    /// The implementation of the JSONRPC module.
    fn into_impl(self) -> jsonrpsee::RpcModule<Self>;
}
