[package]
name = "contra-crypto-fixtures"
version = "0.1.0"
edition = "2024"
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false

[dependencies]
bcs.workspace = true
bulletproofs = "5.0.0"
curve25519-dalek = "4.1"
fastcrypto.workspace = true
merlin = "3.0.0"
rand = { workspace = true, features = ["std_rng"] }

[[bin]]
name = "gen_move_fixtures"
path = "src/bin/gen_move_fixtures.rs"
