[package]
name = "MySoGroups"
version = "0.0.1"
published-at = "0xa11"
edition = "2024"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
MySo = { local = "../myso-framework/myso-framework" }

[addresses]
myso_groups = "0xa11"
