[package]
name = "BridgedBTC"
version = "0.0.1"
edition = "legacy"

[dependencies]
MoveStdlib = { local = "../../../../crates/myso-framework/packages/move-stdlib" }
MySo = { local = "../../../../crates/myso-framework/packages/myso-framework" }

[addresses]
bridged_btc = "0x0"

[environments]
localnet = "7fe1c64b"
testnet = "56a7099f"
