client_metric_host: "127.0.0.1"
client_metric_port: 9185
rpc_api_url: "http://fullnode.testnet.mysocial.network:9000"
streaming_url: "http://fullnode.testnet.mysocial.network:9000"

output_store:
  type: clickhouse
  host: "localhost"
  port: 9000
  user: "default"

pipelines:
  - pipeline: Transaction
    file_format: parquet
    batch_size:
      rows: 100
    force_batch_cut_after_secs: 5
  - pipeline: Event
    file_format: parquet
    batch_size:
      rows: 100
    force_batch_cut_after_secs: 5
  - pipeline: MoveCall
    file_format: parquet
    batch_size:
      rows: 100
    force_batch_cut_after_secs: 5

first_checkpoint: 2587781
